package com.example.Authx.entity;

public enum AuditAction {
    REGISTER,
    LOGIN,
    LOGIN_FAILED,
    LOGOUT,

    EMAIL_VERIFIED,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET,

    REFRESH_TOKEN,
    ACCOUNT_LOCKED,

    MFA_ENABLED,
    MFA_DISABLED,
    MFA_SUCCESS,
    MFA_FAILED,

    OAUTH_LOGIN,
    DELETE_ACCOUNT,

    CREATE_ORGANIZATION,
    UPDATE_ORGANIZATION,
    DELETE_ORGANIZATION,

    INVITE_MEMBER,
    REMOVE_MEMBER,
    CHANGE_ROLE,

    ASSIGN_PERMISSION,
    REVOKE_PERMISSION,

    ACCEPT_INVITE,
    DECLINE_INVITE
}
