# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/authapp
spring.datasource.username=root
spring.datasource.password=mypass 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret.key=mysecretkey123456
server.servlet.context-path=/api/v1.0

